blocksV = [0 1 3 5 6 7];
trianglesV = [2 4];
TableIndex = 8;
onV_start = [0 1; 2 0; 5 3; 6 5; 4 6; 1 8; 3 8; 7 8];
clearV_start = [2 4];
onV_goal = [2 3; 4 1; 1 6];
clearV_goal = [5];
moveActionIndex = 0;
moveToTableActionIndex = 1;
runtest(blocksV, trianglesV, TableIndex, onV_start, clearV_start, onV_goal, clearV_goal, moveActionIndex, moveToTableActionIndex);
